name = "OpenEOClient"
uuid = "453781fe-a3c2-4c28-a19a-0c7c3d89805f"
authors = ["Daniel Loos <dloos@bgc-jena.mpg.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
