# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct AccountManagementApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `AccountManagementApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ AccountManagementApi }) = "https://openeo.example/api/v1"

const _returntypes_authenticate_basic_AccountManagementApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => HTTPBasicAccessToken,
    Regex("^" * replace("4XX", "x"=>".") * "\$") => Error,
    Regex("^" * replace("5XX", "x"=>".") * "\$") => Error,
)

function _oacinternal_authenticate_basic(_api::AccountManagementApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_authenticate_basic_AccountManagementApi, "/credentials/basic", ["Basic", ])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""HTTP Basic authentication

Checks the credentials provided through [HTTP Basic Authentication according to RFC 7617](https://www.rfc-editor.org/rfc/rfc7617.html) and returns an access token for valid credentials.  The credentials (username and password) MUST be sent in the HTTP header `Authorization` with type `Basic` and the Base64 encoded string consisting of username and password separated by a double colon `:`. The header would look as follows for username `user` and password `pw`: `Authorization: Basic dXNlcjpwdw==`.  The access token has to be used in the Bearer token for authorization in subsequent API calls (see also the information about Bearer tokens in this document). The access token returned by this request MUST NOT be provided with `basic//` prefix, but the Bearer Token sent in subsequent API calls to protected endpoints MUST be prefixed with `basic//`. The header in subsequent API calls would look as follows: `Authorization: Bearer basic//TOKEN` (replace `TOKEN` with the actual access token).  It is RECOMMENDED to implement this authentication method for non-public services only.

Params:

Return: HTTPBasicAccessToken, OpenAPI.Clients.ApiResponse
"""
function authenticate_basic(_api::AccountManagementApi; _mediaType=nothing)
    _ctx = _oacinternal_authenticate_basic(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function authenticate_basic(_api::AccountManagementApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_authenticate_basic(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_authenticate_oidc_AccountManagementApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => OpenIDConnectProviders,
    Regex("^" * replace("4XX", "x"=>".") * "\$") => Error,
    Regex("^" * replace("5XX", "x"=>".") * "\$") => Error,
)

function _oacinternal_authenticate_oidc(_api::AccountManagementApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_authenticate_oidc_AccountManagementApi, "/credentials/oidc", [])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""OpenID Connect authentication

Lists the supported [OpenID Connect](http://openid.net/connect/) providers (OP). OpenID Connect Providers MUST support [OpenID Connect Discovery](http://openid.net/specs/openid-connect-discovery-1_0.html).  It is highly RECOMMENDED to implement OpenID Connect for public services in favor of Basic authentication.  openEO clients MUST use the **access token** as part of the Bearer token for authorization in subsequent API calls (see also the information about Bearer tokens in this document). Clients MUST NOT use the id token or the authorization code. The access token provided by an OpenID Connect Provider does not necessarily provide information about the issuer (i.e. the OpenID Connect provider) and therefore a prefix MUST be added to the Bearer Token sent in subsequent API calls to protected endpoints. The Bearer Token sent to protected endpoints MUST consist of the authentication method (here `oidc`), the provider ID and the access token itself. All separated by a forward slash `/`. The provider ID corresponds to the value specified for `id` for each provider in the response body of this endpoint.  The header in subsequent API calls for a provider with `id` `ms` would look as follows: `Authorization: Bearer oidc/ms/TOKEN` (replace `TOKEN` with the actual access token received from the OpenID Connect Provider).  Back-ends MAY request user information ([including Claims](https://openid.net/specs/openid-connect-core-1_0.html#Claims)) from the [OpenID Connect Userinfo endpoint](https://openid.net/specs/openid-connect-core-1_0.html#UserInfo) using the access token (without the prefix described above). Therefore, both openEO client and openEO back-end are relying parties (clients) to the OpenID Connect Provider.

Params:

Return: OpenIDConnectProviders, OpenAPI.Clients.ApiResponse
"""
function authenticate_oidc(_api::AccountManagementApi; _mediaType=nothing)
    _ctx = _oacinternal_authenticate_oidc(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function authenticate_oidc(_api::AccountManagementApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_authenticate_oidc(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_describe_account_AccountManagementApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => UserData,
    Regex("^" * replace("4XX", "x"=>".") * "\$") => Error,
    Regex("^" * replace("5XX", "x"=>".") * "\$") => Error,
)

function _oacinternal_describe_account(_api::AccountManagementApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_describe_account_AccountManagementApi, "/me", ["Bearer", ])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Information about the authenticated user

Lists information about the authenticated user, e.g. the user id. The endpoint MAY return the disk quota available to the user. The endpoint MAY also return links related to user management and the user profile, e.g. where payments are handled or the user profile could be edited. For back-ends that involve accounting, this service MAY also return the currently available money or credits in the currency the back-end is working with. This endpoint MAY be extended to fulfil the specification of the [OpenID Connect UserInfo Endpoint](http://openid.net/specs/openid-connect-core-1_0.html#UserInfo).

Params:

Return: UserData, OpenAPI.Clients.ApiResponse
"""
function describe_account(_api::AccountManagementApi; _mediaType=nothing)
    _ctx = _oacinternal_describe_account(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function describe_account(_api::AccountManagementApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_describe_account(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export authenticate_basic
export authenticate_oidc
export describe_account
