# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""dimension
A dimension, each object represents a distinct dimension with the key being the dimension name.

    Dimension(;
        type=nothing,
        description=nothing,
    )

    - type::String : Type of the dimension.
    - description::String : Detailed description to explain the entity.  [CommonMark 0.29](http://commonmark.org/) syntax MAY be used for rich text representation.
"""
Base.@kwdef mutable struct Dimension <: OpenAPI.APIModel
    type::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing

    function Dimension(type, description, )
        OpenAPI.validate_property(Dimension, Symbol("type"), type)
        OpenAPI.validate_property(Dimension, Symbol("description"), description)
        return new(type, description, )
    end
end # type Dimension

const _property_types_Dimension = Dict{Symbol,String}(Symbol("type")=>"String", Symbol("description")=>"String", )
OpenAPI.property_type(::Type{ Dimension }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Dimension[name]))}

function check_required(o::Dimension)
    o.type === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ Dimension }, name::Symbol, val)
    if name === Symbol("type")
        OpenAPI.validate_param(name, "Dimension", :enum, val, ["spatial", "temporal", "bands", "geometry", "other"])
    end
    if name === Symbol("description")
        OpenAPI.validate_param(name, "Dimension", :format, val, "commonmark")
    end
end
