# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""GeoJsonGeometry

    GeoJsonGeometry(;
        type=nothing,
    )

    - type::GeometryType
"""
Base.@kwdef mutable struct GeoJsonGeometry <: OpenAPI.APIModel
    type = nothing # spec type: Union{ Nothing, GeometryType }

    function GeoJsonGeometry(type, )
        OpenAPI.validate_property(GeoJsonGeometry, Symbol("type"), type)
        return new(type, )
    end
end # type GeoJsonGeometry

const _property_types_GeoJsonGeometry = Dict{Symbol,String}(Symbol("type")=>"GeometryType", )
OpenAPI.property_type(::Type{ GeoJsonGeometry }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GeoJsonGeometry[name]))}

function check_required(o::GeoJsonGeometry)
    o.type === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ GeoJsonGeometry }, name::Symbol, val)
end
