# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""HTTP_Basic_Access_Token

    HTTPBasicAccessToken(;
        access_token=nothing,
    )

    - access_token::String : The access token (without &#x60;basic//&#x60; prefix) to be used in the Bearer token for authorization in subsequent API calls.
"""
Base.@kwdef mutable struct HTTPBasicAccessToken <: OpenAPI.APIModel
    access_token::Union{Nothing, String} = nothing

    function HTTPBasicAccessToken(access_token, )
        OpenAPI.validate_property(HTTPBasicAccessToken, Symbol("access_token"), access_token)
        return new(access_token, )
    end
end # type HTTPBasicAccessToken

const _property_types_HTTPBasicAccessToken = Dict{Symbol,String}(Symbol("access_token")=>"String", )
OpenAPI.property_type(::Type{ HTTPBasicAccessToken }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_HTTPBasicAccessToken[name]))}

function check_required(o::HTTPBasicAccessToken)
    o.access_token === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ HTTPBasicAccessToken }, name::Symbol, val)
end
