# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""User_Storage
Information about the storage space available to the user.

    UserStorage(;
        free=nothing,
        quota=nothing,
    )

    - free::Int64 : Free storage space in bytes, which is still available to the user. Effectively, this is the disk quota minus the used space by the user, e.g. user-uploaded files and job results.
    - quota::Int64 : Maximum storage space (disk quota) in bytes available to the user.
"""
Base.@kwdef mutable struct UserStorage <: OpenAPI.APIModel
    free::Union{Nothing, Int64} = nothing
    quota::Union{Nothing, Int64} = nothing

    function UserStorage(free, quota, )
        OpenAPI.validate_property(UserStorage, Symbol("free"), free)
        OpenAPI.validate_property(UserStorage, Symbol("quota"), quota)
        return new(free, quota, )
    end
end # type UserStorage

const _property_types_UserStorage = Dict{Symbol,String}(Symbol("free")=>"Int64", Symbol("quota")=>"Int64", )
OpenAPI.property_type(::Type{ UserStorage }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UserStorage[name]))}

function check_required(o::UserStorage)
    o.free === nothing && (return false)
    o.quota === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ UserStorage }, name::Symbol, val)
end
