# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""User_Defined_Process
A user-defined process with processing instructions as process graph.

    UserDefinedProcess(;
        id=nothing,
        summary=nothing,
        description=nothing,
        categories=nothing,
        parameters=nothing,
        returns=nothing,
        deprecated=false,
        experimental=false,
        exceptions=nothing,
        examples=nothing,
        links=nothing,
        process_graph=nothing,
    )

    - id::String : The identifier for the process. It MUST be unique across its namespace (e.g. predefined processes or user-defined processes).  Clients SHOULD warn the user if a user-defined process is added with the  same identifier as one of the predefined process.
    - summary::String : A short summary of what the process does.
    - description::String : Detailed description to explain the entity.  [CommonMark 0.29](http://commonmark.org/) syntax MAY be used for rich text representation. In addition to the CommonMark syntax, clients can convert process IDs that are formatted as in the following example into links instead of code blocks: &#x60;&#x60;&#x60; &#x60;&#x60;process_id()&#x60;&#x60; &#x60;&#x60;&#x60;
    - categories::Vector{String} : A list of categories.
    - parameters::Vector{ProcessParameter} : A list of parameters.  The order in the array corresponds to the parameter order to be used in clients that don&#39;t support named parameters.  **Note:** Specifying an empty array is different from (if allowed) &#x60;null&#x60; or the property being absent. An empty array means the process has no parameters. &#x60;null&#x60; / property absent means that the parameters are unknown as the user has not specified them. There could still be parameters in the process graph, if one is specified.
    - returns::ProcessReturnValue
    - deprecated::Bool : Declares that the specified entity is deprecated with the potential to be removed in any of the next versions. It should be transitioned out of usage as soon as possible and users should refrain from using it in new implementations.
    - experimental::Bool : Declares that the specified entity is experimental, which means that it is likely to change or may produce unpredictable behaviour. Users should refrain from using it in production, but still feel encouraged to try it out and give feedback.
    - exceptions::Dict{String, ProcessExceptions} : Declares exceptions (errors) that might occur during execution of this process. This list is just for informative purposes and may be incomplete. This list MUST only contain exceptions that stop the execution of a process and MUST NOT contain warnings, notices or debugging messages. It is meant to primarily contain errors that have been caused by the user. It is RECOMMENDED that exceptions are referred to and explained in process or parameter descriptions.  The keys define the error code and MUST match the following pattern: &#x60;^\\w+$&#x60;  This schema follows the schema of the general openEO error list (see errors.json).
    - examples::Vector{ProcessExample} : Examples, may be used for unit tests.
    - links::Vector{Link} : Links related to this process, e.g. additional external documentation.  It is RECOMMENDED to provide links with the following &#x60;rel&#x60; (relation) types:  1. &#x60;latest-version&#x60;: If a process has been marked as deprecated, a link SHOULD point to the preferred version of the process. The relation types &#x60;predecessor-version&#x60; (link to older version) and &#x60;successor-version&#x60; (link to newer version) can also be used to show the relation between versions.  2. &#x60;example&#x60;: Links to examples of other processes that use this process.  3. &#x60;cite-as&#x60;: For all DOIs associated with the process, the respective DOI links SHOULD be added.  For additional relation types see also the lists of [common relation types in openEO](#section/API-Principles/Web-Linking).
    - process_graph::Dict{String, ProcessGraph} : A process graph defines a graph-like structure as a connected set of executable processes. Each key is a unique identifier (node ID) that is used to refer to the process in the graph.
"""
Base.@kwdef mutable struct UserDefinedProcess <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    summary::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    categories::Union{Nothing, Vector{String}} = nothing
    parameters::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ProcessParameter} }
    returns = nothing # spec type: Union{ Nothing, ProcessReturnValue }
    deprecated::Union{Nothing, Bool} = false
    experimental::Union{Nothing, Bool} = false
    exceptions::Union{Nothing, Dict} = nothing # spec type: Union{ Nothing, Dict{String, ProcessExceptions} }
    examples::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ProcessExample} }
    links::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{Link} }
    process_graph::Union{Nothing, Dict} = nothing # spec type: Union{ Nothing, Dict{String, ProcessGraph} }

    function UserDefinedProcess(id, summary, description, categories, parameters, returns, deprecated, experimental, exceptions, examples, links, process_graph, )
        OpenAPI.validate_property(UserDefinedProcess, Symbol("id"), id)
        OpenAPI.validate_property(UserDefinedProcess, Symbol("summary"), summary)
        OpenAPI.validate_property(UserDefinedProcess, Symbol("description"), description)
        OpenAPI.validate_property(UserDefinedProcess, Symbol("categories"), categories)
        OpenAPI.validate_property(UserDefinedProcess, Symbol("parameters"), parameters)
        OpenAPI.validate_property(UserDefinedProcess, Symbol("returns"), returns)
        OpenAPI.validate_property(UserDefinedProcess, Symbol("deprecated"), deprecated)
        OpenAPI.validate_property(UserDefinedProcess, Symbol("experimental"), experimental)
        OpenAPI.validate_property(UserDefinedProcess, Symbol("exceptions"), exceptions)
        OpenAPI.validate_property(UserDefinedProcess, Symbol("examples"), examples)
        OpenAPI.validate_property(UserDefinedProcess, Symbol("links"), links)
        OpenAPI.validate_property(UserDefinedProcess, Symbol("process_graph"), process_graph)
        return new(id, summary, description, categories, parameters, returns, deprecated, experimental, exceptions, examples, links, process_graph, )
    end
end # type UserDefinedProcess

const _property_types_UserDefinedProcess = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("summary")=>"String", Symbol("description")=>"String", Symbol("categories")=>"Vector{String}", Symbol("parameters")=>"Vector{ProcessParameter}", Symbol("returns")=>"ProcessReturnValue", Symbol("deprecated")=>"Bool", Symbol("experimental")=>"Bool", Symbol("exceptions")=>"Dict{String, ProcessExceptions}", Symbol("examples")=>"Vector{ProcessExample}", Symbol("links")=>"Vector{Link}", Symbol("process_graph")=>"Dict{String, ProcessGraph}", )
OpenAPI.property_type(::Type{ UserDefinedProcess }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UserDefinedProcess[name]))}

function check_required(o::UserDefinedProcess)
    o.id === nothing && (return false)
    o.process_graph === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ UserDefinedProcess }, name::Symbol, val)
    if name === Symbol("id")
        OpenAPI.validate_param(name, "UserDefinedProcess", :pattern, val, r"^\w+$")
    end
    if name === Symbol("description")
        OpenAPI.validate_param(name, "UserDefinedProcess", :format, val, "commonmark")
    end
end
