# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Result_Reference
Data that is expected to be passed from another process.

    ResultReference(;
        from_node=nothing,
    )

    - from_node::String : The ID of the node that data is expected to come from.
"""
Base.@kwdef mutable struct ResultReference <: OpenAPI.APIModel
    from_node::Union{Nothing, String} = nothing

    function ResultReference(from_node, )
        OpenAPI.validate_property(ResultReference, Symbol("from_node"), from_node)
        return new(from_node, )
    end
end # type ResultReference

const _property_types_ResultReference = Dict{Symbol,String}(Symbol("from_node")=>"String", )
OpenAPI.property_type(::Type{ ResultReference }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ResultReference[name]))}

function check_required(o::ResultReference)
    o.from_node === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ResultReference }, name::Symbol, val)
end
