# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Well_Known_Discovery

    WellKnownDiscovery(;
        versions=nothing,
    )

    - versions::Vector{APIInstance}
"""
Base.@kwdef mutable struct WellKnownDiscovery <: OpenAPI.APIModel
    versions::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{APIInstance} }

    function WellKnownDiscovery(versions, )
        OpenAPI.validate_property(WellKnownDiscovery, Symbol("versions"), versions)
        return new(versions, )
    end
end # type WellKnownDiscovery

const _property_types_WellKnownDiscovery = Dict{Symbol,String}(Symbol("versions")=>"Vector{APIInstance}", )
OpenAPI.property_type(::Type{ WellKnownDiscovery }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_WellKnownDiscovery[name]))}

function check_required(o::WellKnownDiscovery)
    o.versions === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ WellKnownDiscovery }, name::Symbol, val)
end
