# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""list_results_200_response

    ListResults200Response(; value=nothing)
"""
mutable struct ListResults200Response <: OpenAPI.OneOfAPIModel
    value::Any # Union{ BatchJobResult, BatchJobResultsResponseAsSTACCollection }
    ListResults200Response() = new()
    ListResults200Response(value) = new(value)
end # type ListResults200Response

function OpenAPI.property_type(::Type{ ListResults200Response }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(ListResults200Response, name)
end
