# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Update_Secondary_Web_Service_Request

    UpdateSecondaryWebServiceRequest(;
        title=nothing,
        description=nothing,
        process=nothing,
        enabled=nothing,
        configuration=nothing,
        plan=nothing,
        budget=nothing,
        log_level=nothing,
    )

    - title::String : A short description to easily distinguish entities.
    - description::String : Detailed multi-line description to explain the entity.  [CommonMark 0.29](http://commonmark.org/) syntax MAY be used for rich text representation.
    - process::ProcessGraphWithMetadata
    - enabled::Bool : Describes whether a secondary web service is responding to requests (true) or not (false). Disabled services don&#39;t produce any costs.
    - configuration::Any : Map of configuration settings, i.e. the setting names supported by the secondary web service combined with actual values. See &#x60;GET /service_types&#x60; for supported configuration settings. For example, this could specify the required version of the service, visualization details or any other service dependant configuration.
    - plan::String : The billing plan to process and charge the job or service with.  Billing plans MUST be accepted in a *case insensitive* manner. Back-ends MUST resolve the billing plan in the following way if billing is supported:  * If a value is given and it is not &#x60;null&#x60;: Persist the &#x60;plan&#x60; that has been provided in the request. * Otherwise, don&#39;t change the billing plan.  Billing plans not on the list of available plans MUST be rejected with openEO error &#x60;BillingPlanInvalid&#x60;.
    - budget::Float64 : Maximum amount of costs the request is allowed to produce. The value MUST be specified in the currency of the back-end. No limits apply, if the value is &#x60;null&#x60;.
    - log_level::MinLogLevelUpdate
"""
Base.@kwdef mutable struct UpdateSecondaryWebServiceRequest <: OpenAPI.APIModel
    title::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    process = nothing # spec type: Union{ Nothing, ProcessGraphWithMetadata }
    enabled::Union{Nothing, Bool} = nothing
    configuration::Union{Nothing, Any} = nothing
    plan::Union{Nothing, String} = nothing
    budget::Union{Nothing, Float64} = nothing
    log_level = nothing # spec type: Union{ Nothing, MinLogLevelUpdate }

    function UpdateSecondaryWebServiceRequest(title, description, process, enabled, configuration, plan, budget, log_level, )
        OpenAPI.validate_property(UpdateSecondaryWebServiceRequest, Symbol("title"), title)
        OpenAPI.validate_property(UpdateSecondaryWebServiceRequest, Symbol("description"), description)
        OpenAPI.validate_property(UpdateSecondaryWebServiceRequest, Symbol("process"), process)
        OpenAPI.validate_property(UpdateSecondaryWebServiceRequest, Symbol("enabled"), enabled)
        OpenAPI.validate_property(UpdateSecondaryWebServiceRequest, Symbol("configuration"), configuration)
        OpenAPI.validate_property(UpdateSecondaryWebServiceRequest, Symbol("plan"), plan)
        OpenAPI.validate_property(UpdateSecondaryWebServiceRequest, Symbol("budget"), budget)
        OpenAPI.validate_property(UpdateSecondaryWebServiceRequest, Symbol("log_level"), log_level)
        return new(title, description, process, enabled, configuration, plan, budget, log_level, )
    end
end # type UpdateSecondaryWebServiceRequest

const _property_types_UpdateSecondaryWebServiceRequest = Dict{Symbol,String}(Symbol("title")=>"String", Symbol("description")=>"String", Symbol("process")=>"ProcessGraphWithMetadata", Symbol("enabled")=>"Bool", Symbol("configuration")=>"Any", Symbol("plan")=>"String", Symbol("budget")=>"Float64", Symbol("log_level")=>"MinLogLevelUpdate", )
OpenAPI.property_type(::Type{ UpdateSecondaryWebServiceRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UpdateSecondaryWebServiceRequest[name]))}

function check_required(o::UpdateSecondaryWebServiceRequest)
    true
end

function OpenAPI.validate_property(::Type{ UpdateSecondaryWebServiceRequest }, name::Symbol, val)
    if name === Symbol("description")
        OpenAPI.validate_param(name, "UpdateSecondaryWebServiceRequest", :format, val, "commonmark")
    end
    if name === Symbol("budget")
        OpenAPI.validate_param(name, "UpdateSecondaryWebServiceRequest", :minimum, val, 0, false)
    end
end
