# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""batch_job_usage
Metrics about the resource usage of the batch job.  Back-ends are not expected to update the metrics while processing data, so the metrics can only be available after the job has finished or has stopped due to an error. For usage metrics during processing, metrics can better be added to the logs (e.g. &#x60;GET /jobs/{job_id}/logs&#x60;) with the same schema.

    BatchJobUsage(;
        cpu=nothing,
        memory=nothing,
        duration=nothing,
        network=nothing,
        disk=nothing,
        storage=nothing,
    )

    - cpu::UsageCpu
    - memory::UsageMemory
    - duration::UsageDuration
    - network::UsageNetwork
    - disk::UsageDisk
    - storage::UsageStorage
"""
Base.@kwdef mutable struct BatchJobUsage <: OpenAPI.APIModel
    cpu = nothing # spec type: Union{ Nothing, UsageCpu }
    memory = nothing # spec type: Union{ Nothing, UsageMemory }
    duration = nothing # spec type: Union{ Nothing, UsageDuration }
    network = nothing # spec type: Union{ Nothing, UsageNetwork }
    disk = nothing # spec type: Union{ Nothing, UsageDisk }
    storage = nothing # spec type: Union{ Nothing, UsageStorage }

    function BatchJobUsage(cpu, memory, duration, network, disk, storage, )
        OpenAPI.validate_property(BatchJobUsage, Symbol("cpu"), cpu)
        OpenAPI.validate_property(BatchJobUsage, Symbol("memory"), memory)
        OpenAPI.validate_property(BatchJobUsage, Symbol("duration"), duration)
        OpenAPI.validate_property(BatchJobUsage, Symbol("network"), network)
        OpenAPI.validate_property(BatchJobUsage, Symbol("disk"), disk)
        OpenAPI.validate_property(BatchJobUsage, Symbol("storage"), storage)
        return new(cpu, memory, duration, network, disk, storage, )
    end
end # type BatchJobUsage

const _property_types_BatchJobUsage = Dict{Symbol,String}(Symbol("cpu")=>"UsageCpu", Symbol("memory")=>"UsageMemory", Symbol("duration")=>"UsageDuration", Symbol("network")=>"UsageNetwork", Symbol("disk")=>"UsageDisk", Symbol("storage")=>"UsageStorage", )
OpenAPI.property_type(::Type{ BatchJobUsage }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchJobUsage[name]))}

function check_required(o::BatchJobUsage)
    true
end

function OpenAPI.validate_property(::Type{ BatchJobUsage }, name::Symbol, val)
end
