# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""process_schema
Either a single data type or a list of data types for process parameter or process return values.

    ProcessSchema(; value=nothing)
"""
mutable struct ProcessSchema <: OpenAPI.OneOfAPIModel
    value::Any # Union{ ProcessJsonSchema, Vector{ProcessJsonSchema} }
    ProcessSchema() = new()
    ProcessSchema(value) = new(value)
end # type ProcessSchema

function OpenAPI.property_type(::Type{ ProcessSchema }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(ProcessSchema, name)
end
