# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""GeoJson

    GeoJson(; value=nothing)
"""
mutable struct GeoJson <: OpenAPI.OneOfAPIModel
    value::Any # Union{ GeoJsonFeature, GeoJsonFeatureCollection, GeoJsonGeometry }
    GeoJson() = new()
    GeoJson(value) = new(value)
end # type GeoJson

function OpenAPI.property_type(::Type{ GeoJson }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(GeoJson, name)
end
