# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""GeoJsonMultiLineString

    GeoJsonMultiLineString(;
        type=nothing,
        coordinates=nothing,
    )

    - type::GeometryType
    - coordinates::Vector{Vector{Vector}}
"""
Base.@kwdef mutable struct GeoJsonMultiLineString <: OpenAPI.APIModel
    type = nothing # spec type: Union{ Nothing, GeometryType }
    coordinates::Union{Nothing, Vector{Vector{Vector}}} = nothing

    function GeoJsonMultiLineString(type, coordinates, )
        OpenAPI.validate_property(GeoJsonMultiLineString, Symbol("type"), type)
        OpenAPI.validate_property(GeoJsonMultiLineString, Symbol("coordinates"), coordinates)
        return new(type, coordinates, )
    end
end # type GeoJsonMultiLineString

const _property_types_GeoJsonMultiLineString = Dict{Symbol,String}(Symbol("type")=>"GeometryType", Symbol("coordinates")=>"Vector{Vector{Vector}}", )
OpenAPI.property_type(::Type{ GeoJsonMultiLineString }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GeoJsonMultiLineString[name]))}

function check_required(o::GeoJsonMultiLineString)
    o.type === nothing && (return false)
    o.coordinates === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ GeoJsonMultiLineString }, name::Symbol, val)
end
