# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""usage_cpu
Specifies the CPU usage, usually in a unit such as &#x60;cpu-seconds&#x60;.

    UsageCpu(;
        value=nothing,
        unit=nothing,
    )

    - value::Float64
    - unit::String
"""
Base.@kwdef mutable struct UsageCpu <: OpenAPI.APIModel
    value::Union{Nothing, Float64} = nothing
    unit::Union{Nothing, String} = nothing

    function UsageCpu(value, unit, )
        OpenAPI.validate_property(UsageCpu, Symbol("value"), value)
        OpenAPI.validate_property(UsageCpu, Symbol("unit"), unit)
        return new(value, unit, )
    end
end # type UsageCpu

const _property_types_UsageCpu = Dict{Symbol,String}(Symbol("value")=>"Float64", Symbol("unit")=>"String", )
OpenAPI.property_type(::Type{ UsageCpu }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UsageCpu[name]))}

function check_required(o::UsageCpu)
    o.value === nothing && (return false)
    o.unit === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ UsageCpu }, name::Symbol, val)
    if name === Symbol("value")
        OpenAPI.validate_param(name, "UsageCpu", :minimum, val, 0, false)
    end
end
