# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


if !isdefined(@__MODULE__, :GeometryType)
    const GeometryType = String
else
    @warn("Skipping redefinition of GeometryType to String")
end
