# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""usage_duration
Specifies the wall time, usually in a unit such as &#x60;seconds&#x60;, &#x60;minutes&#x60; or &#x60;hours&#x60;.

    UsageDuration(;
        value=nothing,
        unit=nothing,
    )

    - value::Float64
    - unit::String
"""
Base.@kwdef mutable struct UsageDuration <: OpenAPI.APIModel
    value::Union{Nothing, Float64} = nothing
    unit::Union{Nothing, String} = nothing

    function UsageDuration(value, unit, )
        OpenAPI.validate_property(UsageDuration, Symbol("value"), value)
        OpenAPI.validate_property(UsageDuration, Symbol("unit"), unit)
        return new(value, unit, )
    end
end # type UsageDuration

const _property_types_UsageDuration = Dict{Symbol,String}(Symbol("value")=>"Float64", Symbol("unit")=>"String", )
OpenAPI.property_type(::Type{ UsageDuration }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UsageDuration[name]))}

function check_required(o::UsageDuration)
    o.value === nothing && (return false)
    o.unit === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ UsageDuration }, name::Symbol, val)
    if name === Symbol("value")
        OpenAPI.validate_param(name, "UsageDuration", :minimum, val, 0, false)
    end
end
