# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""json_schema_type_1
The allowed basic data type(s) for a value.  If this property is not present, all data types are allowed.

    JsonSchemaType1(; value=nothing)
"""
mutable struct JsonSchemaType1 <: OpenAPI.OneOfAPIModel
    value::Any # Union{ JsonSchemaType, Vector{JsonSchemaType} }
    JsonSchemaType1() = new()
    JsonSchemaType1(value) = new(value)
end # type JsonSchemaType1

function OpenAPI.property_type(::Type{ JsonSchemaType1 }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(JsonSchemaType1, name)
end
