# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""collection_summary_stats_minimum
The minimum value (inclusive).

    CollectionSummaryStatsMinimum(; value=nothing)
"""
mutable struct CollectionSummaryStatsMinimum <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Float64, String }
    CollectionSummaryStatsMinimum() = new()
    CollectionSummaryStatsMinimum(value) = new(value)
end # type CollectionSummaryStatsMinimum

function OpenAPI.property_type(::Type{ CollectionSummaryStatsMinimum }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(CollectionSummaryStatsMinimum, name)
end
