# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Parameter_Reference
A parameter for a process graph. Data that is expected to be passed to a process graph either from the user directly or from the process that is executing the process graph.

    ParameterReference(;
        from_parameter=nothing,
    )

    - from_parameter::String : The name of the parameter that data is expected to come from.
"""
Base.@kwdef mutable struct ParameterReference <: OpenAPI.APIModel
    from_parameter::Union{Nothing, String} = nothing

    function ParameterReference(from_parameter, )
        OpenAPI.validate_property(ParameterReference, Symbol("from_parameter"), from_parameter)
        return new(from_parameter, )
    end
end # type ParameterReference

const _property_types_ParameterReference = Dict{Symbol,String}(Symbol("from_parameter")=>"String", )
OpenAPI.property_type(::Type{ ParameterReference }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ParameterReference[name]))}

function check_required(o::ParameterReference)
    o.from_parameter === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ParameterReference }, name::Symbol, val)
end
