# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Store_Batch_Job_Request

    StoreBatchJobRequest(;
        title=nothing,
        description=nothing,
        process=nothing,
        plan=nothing,
        budget=nothing,
        log_level=nothing,
    )

    - title::String : A short description to easily distinguish entities.
    - description::String : Detailed multi-line description to explain the entity.  [CommonMark 0.29](http://commonmark.org/) syntax MAY be used for rich text representation.
    - process::ProcessGraphWithMetadata
    - plan::String : The billing plan to process and charge the job or service with.  Billing plans MUST be accepted in a *case insensitive* manner. Back-ends MUST resolve the billing plan in the following way:  * If a non-&#x60;null&#x60; value is given: Persist the &#x60;plan&#x60; that has been provided in the request. * Otherwise:   1. Persist the &#x60;default_plan&#x60; exposed through &#x60;GET /me&#x60;, if available.   2. Persist the &#x60;default_plan&#x60; exposed through &#x60;GET /&#x60;, if available.   3. If a single plan is exposed by the back-end, persist it.   4. Otherwise, the back-end MUST throw a &#x60;BillingPlanMissing&#x60; error.  The resolved plan MUST be persisted permanently, regardless of any  changes to the exposed billing plans in &#x60;GET /&#x60; in the future.  Billing plans not on the list of available plans MUST be rejected with openEO error &#x60;BillingPlanInvalid&#x60;.
    - budget::Float64 : Maximum amount of costs the request is allowed to produce. The value MUST be specified in the currency of the back-end. No limits apply, if the value is &#x60;null&#x60; or the back-end has no currency set in &#x60;GET /&#x60;.
    - log_level::MinLogLevelDefault
"""
Base.@kwdef mutable struct StoreBatchJobRequest <: OpenAPI.APIModel
    title::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    process = nothing # spec type: Union{ Nothing, ProcessGraphWithMetadata }
    plan::Union{Nothing, String} = nothing
    budget::Union{Nothing, Float64} = nothing
    log_level = nothing # spec type: Union{ Nothing, MinLogLevelDefault }

    function StoreBatchJobRequest(title, description, process, plan, budget, log_level, )
        OpenAPI.validate_property(StoreBatchJobRequest, Symbol("title"), title)
        OpenAPI.validate_property(StoreBatchJobRequest, Symbol("description"), description)
        OpenAPI.validate_property(StoreBatchJobRequest, Symbol("process"), process)
        OpenAPI.validate_property(StoreBatchJobRequest, Symbol("plan"), plan)
        OpenAPI.validate_property(StoreBatchJobRequest, Symbol("budget"), budget)
        OpenAPI.validate_property(StoreBatchJobRequest, Symbol("log_level"), log_level)
        return new(title, description, process, plan, budget, log_level, )
    end
end # type StoreBatchJobRequest

const _property_types_StoreBatchJobRequest = Dict{Symbol,String}(Symbol("title")=>"String", Symbol("description")=>"String", Symbol("process")=>"ProcessGraphWithMetadata", Symbol("plan")=>"String", Symbol("budget")=>"Float64", Symbol("log_level")=>"MinLogLevelDefault", )
OpenAPI.property_type(::Type{ StoreBatchJobRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_StoreBatchJobRequest[name]))}

function check_required(o::StoreBatchJobRequest)
    o.process === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ StoreBatchJobRequest }, name::Symbol, val)
    if name === Symbol("description")
        OpenAPI.validate_param(name, "StoreBatchJobRequest", :format, val, "commonmark")
    end
    if name === Symbol("budget")
        OpenAPI.validate_param(name, "StoreBatchJobRequest", :minimum, val, 0, false)
    end
end
