# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""GeoJsonLineString

    GeoJsonLineString(;
        type=nothing,
        coordinates=nothing,
    )

    - type::GeometryType
    - coordinates::Vector{Vector}
"""
Base.@kwdef mutable struct GeoJsonLineString <: OpenAPI.APIModel
    type = nothing # spec type: Union{ Nothing, GeometryType }
    coordinates::Union{Nothing, Vector{Vector}} = nothing

    function GeoJsonLineString(type, coordinates, )
        OpenAPI.validate_property(GeoJsonLineString, Symbol("type"), type)
        OpenAPI.validate_property(GeoJsonLineString, Symbol("coordinates"), coordinates)
        return new(type, coordinates, )
    end
end # type GeoJsonLineString

const _property_types_GeoJsonLineString = Dict{Symbol,String}(Symbol("type")=>"GeometryType", Symbol("coordinates")=>"Vector{Vector}", )
OpenAPI.property_type(::Type{ GeoJsonLineString }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GeoJsonLineString[name]))}

function check_required(o::GeoJsonLineString)
    o.type === nothing && (return false)
    o.coordinates === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ GeoJsonLineString }, name::Symbol, val)
end
