# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""collection_summary_stats
By default, only ranges with a minimum and a maximum value can be specified. Ranges can be specified for ordinal values only, which means they need to have a rank order. Therefore, ranges can only be specified for numbers and some special types of strings. Examples: grades (A to F), dates or times. Implementors are free to add other derived statistical values to the object, for example &#x60;mean&#x60; or &#x60;stddev&#x60;.

    CollectionSummaryStats(;
        minimum=nothing,
        maximum=nothing,
    )

    - minimum::CollectionSummaryStatsMinimum
    - maximum::CollectionSummaryStatsMaximum
"""
Base.@kwdef mutable struct CollectionSummaryStats <: OpenAPI.APIModel
    minimum = nothing # spec type: Union{ Nothing, CollectionSummaryStatsMinimum }
    maximum = nothing # spec type: Union{ Nothing, CollectionSummaryStatsMaximum }

    function CollectionSummaryStats(minimum, maximum, )
        OpenAPI.validate_property(CollectionSummaryStats, Symbol("minimum"), minimum)
        OpenAPI.validate_property(CollectionSummaryStats, Symbol("maximum"), maximum)
        return new(minimum, maximum, )
    end
end # type CollectionSummaryStats

const _property_types_CollectionSummaryStats = Dict{Symbol,String}(Symbol("minimum")=>"CollectionSummaryStatsMinimum", Symbol("maximum")=>"CollectionSummaryStatsMaximum", )
OpenAPI.property_type(::Type{ CollectionSummaryStats }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CollectionSummaryStats[name]))}

function check_required(o::CollectionSummaryStats)
    o.minimum === nothing && (return false)
    o.maximum === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CollectionSummaryStats }, name::Symbol, val)
end
