# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""STAC_Summaries__Collection_Properties_

    STACSummariesCollectionProperties(; value=nothing)
"""
mutable struct STACSummariesCollectionProperties <: OpenAPI.OneOfAPIModel
    value::Any # Union{ CollectionSummaryStats, JsonSchema, Vector{Any} }
    STACSummariesCollectionProperties() = new()
    STACSummariesCollectionProperties(value) = new(value)
end # type STACSummariesCollectionProperties

function OpenAPI.property_type(::Type{ STACSummariesCollectionProperties }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(STACSummariesCollectionProperties, name)
end
