# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Programming_language_library

    ProgrammingLanguageLibrary(;
        version=nothing,
        deprecated=false,
        experimental=false,
        links=nothing,
    )

    - version::String : Version number of the library.
    - deprecated::Bool : Declares that the specified entity is deprecated with the potential to be removed in any of the next versions. It should be transitioned out of usage as soon as possible and users should refrain from using it in new implementations.
    - experimental::Bool : Declares that the specified entity is experimental, which means that it is likely to change or may produce unpredictable behaviour. Users should refrain from using it in production, but still feel encouraged to try it out and give feedback.
    - links::Vector{Link} : Additional links related to this library, e.g. external documentation for this library.  It is highly RECOMMENDED to provide links with the following &#x60;rel&#x60; (relation) types:  1. &#x60;about&#x60;: A resource that further explains the library, e.g. a user guide or the documentation. It is RECOMMENDED to  add descriptive titles for a better user experience.  2. &#x60;latest-version&#x60;: If a library has been marked as deprecated, a link SHOULD point to either a new library replacing the deprecated library or a latest version of the library available at the back-end.  For additional relation types see also the lists of [common relation types in openEO](#section/API-Principles/Web-Linking).
"""
Base.@kwdef mutable struct ProgrammingLanguageLibrary <: OpenAPI.APIModel
    version::Union{Nothing, String} = nothing
    deprecated::Union{Nothing, Bool} = false
    experimental::Union{Nothing, Bool} = false
    links::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{Link} }

    function ProgrammingLanguageLibrary(version, deprecated, experimental, links, )
        OpenAPI.validate_property(ProgrammingLanguageLibrary, Symbol("version"), version)
        OpenAPI.validate_property(ProgrammingLanguageLibrary, Symbol("deprecated"), deprecated)
        OpenAPI.validate_property(ProgrammingLanguageLibrary, Symbol("experimental"), experimental)
        OpenAPI.validate_property(ProgrammingLanguageLibrary, Symbol("links"), links)
        return new(version, deprecated, experimental, links, )
    end
end # type ProgrammingLanguageLibrary

const _property_types_ProgrammingLanguageLibrary = Dict{Symbol,String}(Symbol("version")=>"String", Symbol("deprecated")=>"Bool", Symbol("experimental")=>"Bool", Symbol("links")=>"Vector{Link}", )
OpenAPI.property_type(::Type{ ProgrammingLanguageLibrary }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ProgrammingLanguageLibrary[name]))}

function check_required(o::ProgrammingLanguageLibrary)
    o.version === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ProgrammingLanguageLibrary }, name::Symbol, val)
end
