# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""usage

    Usage(;
        cpu=nothing,
        memory=nothing,
        duration=nothing,
        network=nothing,
        disk=nothing,
        storage=nothing,
    )

    - cpu::UsageCpu
    - memory::UsageMemory
    - duration::UsageDuration
    - network::UsageNetwork
    - disk::UsageDisk
    - storage::UsageStorage
"""
Base.@kwdef mutable struct Usage <: OpenAPI.APIModel
    cpu = nothing # spec type: Union{ Nothing, UsageCpu }
    memory = nothing # spec type: Union{ Nothing, UsageMemory }
    duration = nothing # spec type: Union{ Nothing, UsageDuration }
    network = nothing # spec type: Union{ Nothing, UsageNetwork }
    disk = nothing # spec type: Union{ Nothing, UsageDisk }
    storage = nothing # spec type: Union{ Nothing, UsageStorage }

    function Usage(cpu, memory, duration, network, disk, storage, )
        OpenAPI.validate_property(Usage, Symbol("cpu"), cpu)
        OpenAPI.validate_property(Usage, Symbol("memory"), memory)
        OpenAPI.validate_property(Usage, Symbol("duration"), duration)
        OpenAPI.validate_property(Usage, Symbol("network"), network)
        OpenAPI.validate_property(Usage, Symbol("disk"), disk)
        OpenAPI.validate_property(Usage, Symbol("storage"), storage)
        return new(cpu, memory, duration, network, disk, storage, )
    end
end # type Usage

const _property_types_Usage = Dict{Symbol,String}(Symbol("cpu")=>"UsageCpu", Symbol("memory")=>"UsageMemory", Symbol("duration")=>"UsageDuration", Symbol("network")=>"UsageNetwork", Symbol("disk")=>"UsageDisk", Symbol("storage")=>"UsageStorage", )
OpenAPI.property_type(::Type{ Usage }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Usage[name]))}

function check_required(o::Usage)
    true
end

function OpenAPI.validate_property(::Type{ Usage }, name::Symbol, val)
end
