# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Resource_usage_metrics
Additional metrics.

    ResourceUsageMetrics(;
        value=nothing,
        unit=nothing,
    )

    - value::Float64
    - unit::String
"""
Base.@kwdef mutable struct ResourceUsageMetrics <: OpenAPI.APIModel
    value::Union{Nothing, Float64} = nothing
    unit::Union{Nothing, String} = nothing

    function ResourceUsageMetrics(value, unit, )
        OpenAPI.validate_property(ResourceUsageMetrics, Symbol("value"), value)
        OpenAPI.validate_property(ResourceUsageMetrics, Symbol("unit"), unit)
        return new(value, unit, )
    end
end # type ResourceUsageMetrics

const _property_types_ResourceUsageMetrics = Dict{Symbol,String}(Symbol("value")=>"Float64", Symbol("unit")=>"String", )
OpenAPI.property_type(::Type{ ResourceUsageMetrics }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ResourceUsageMetrics[name]))}

function check_required(o::ResourceUsageMetrics)
    o.value === nothing && (return false)
    o.unit === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ResourceUsageMetrics }, name::Symbol, val)
    if name === Symbol("value")
        OpenAPI.validate_param(name, "ResourceUsageMetrics", :minimum, val, 0, false)
    end
end
