# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""OGC_Conformance_Classes

    OGCConformanceClasses(;
        conformsTo=nothing,
    )

    - conformsTo::Vector{String} : Lists all conformance classes specified in various standards that the implementation conforms to. Conformance classes are commonly used in all OGC APIs and the STAC API specification.  The general openEO conformance class is &#x60;https://api.openeo.org/1.2.0&#x60;. See the individual openEO API extensions for their conformance classes.  This property is REQUIRED for STAC API versions 1.0.0-beta.1 and later.
"""
Base.@kwdef mutable struct OGCConformanceClasses <: OpenAPI.APIModel
    conformsTo::Union{Nothing, Vector{String}} = nothing

    function OGCConformanceClasses(conformsTo, )
        OpenAPI.validate_property(OGCConformanceClasses, Symbol("conformsTo"), conformsTo)
        return new(conformsTo, )
    end
end # type OGCConformanceClasses

const _property_types_OGCConformanceClasses = Dict{Symbol,String}(Symbol("conformsTo")=>"Vector{String}", )
OpenAPI.property_type(::Type{ OGCConformanceClasses }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OGCConformanceClasses[name]))}

function check_required(o::OGCConformanceClasses)
    o.conformsTo === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ OGCConformanceClasses }, name::Symbol, val)
end
