# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""collection_dimension_values_inner

    CollectionDimensionValuesInner(; value=nothing)
"""
mutable struct CollectionDimensionValuesInner <: OpenAPI.OneOfAPIModel
    value::Any # Union{ Float64, String }
    CollectionDimensionValuesInner() = new()
    CollectionDimensionValuesInner(value) = new(value)
end # type CollectionDimensionValuesInner

function OpenAPI.property_type(::Type{ CollectionDimensionValuesInner }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(CollectionDimensionValuesInner, name)
end
