# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""GeoJsonMultiPolygon

    GeoJsonMultiPolygon(;
        type=nothing,
        coordinates=nothing,
    )

    - type::GeometryType
    - coordinates::Vector{Vector{Vector{Vector}}}
"""
Base.@kwdef mutable struct GeoJsonMultiPolygon <: OpenAPI.APIModel
    type = nothing # spec type: Union{ Nothing, GeometryType }
    coordinates::Union{Nothing, Vector{Vector{Vector{Vector}}}} = nothing

    function GeoJsonMultiPolygon(type, coordinates, )
        OpenAPI.validate_property(GeoJsonMultiPolygon, Symbol("type"), type)
        OpenAPI.validate_property(GeoJsonMultiPolygon, Symbol("coordinates"), coordinates)
        return new(type, coordinates, )
    end
end # type GeoJsonMultiPolygon

const _property_types_GeoJsonMultiPolygon = Dict{Symbol,String}(Symbol("type")=>"GeometryType", Symbol("coordinates")=>"Vector{Vector{Vector{Vector}}}", )
OpenAPI.property_type(::Type{ GeoJsonMultiPolygon }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GeoJsonMultiPolygon[name]))}

function check_required(o::GeoJsonMultiPolygon)
    o.type === nothing && (return false)
    o.coordinates === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ GeoJsonMultiPolygon }, name::Symbol, val)
end
