# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""collection_dimension_srs
The spatial reference system for the data, specified as [EPSG code](http://www.epsg-registry.org/), [WKT2 (ISO 19162) string](http://docs.opengeospatial.org/is/18-010r7/18-010r7.html), [PROJJSON object](https://proj.org/specifications/projjson.html) or [PROJ definition (deprecated)](https://proj.org/usage/quickstart.html). Defaults to EPSG code 4326.

    CollectionDimensionSrs(; value=nothing)
"""
mutable struct CollectionDimensionSrs <: OpenAPI.OneOfAPIModel
    value::Any # Union{ Any, Float64, String }
    CollectionDimensionSrs() = new()
    CollectionDimensionSrs(value) = new(value)
end # type CollectionDimensionSrs

function OpenAPI.property_type(::Type{ CollectionDimensionSrs }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(CollectionDimensionSrs, name)
end
