# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""usage_storage
Specifies the usage of storage space, usually in a unit such as &#x60;b&#x60; (bytes), &#x60;kb&#x60; (kilobytes), &#x60;mb&#x60; (megabytes) or &#x60;gb&#x60; (gigabytes).

    UsageStorage(;
        value=nothing,
        unit=nothing,
    )

    - value::Float64
    - unit::String
"""
Base.@kwdef mutable struct UsageStorage <: OpenAPI.APIModel
    value::Union{Nothing, Float64} = nothing
    unit::Union{Nothing, String} = nothing

    function UsageStorage(value, unit, )
        OpenAPI.validate_property(UsageStorage, Symbol("value"), value)
        OpenAPI.validate_property(UsageStorage, Symbol("unit"), unit)
        return new(value, unit, )
    end
end # type UsageStorage

const _property_types_UsageStorage = Dict{Symbol,String}(Symbol("value")=>"Float64", Symbol("unit")=>"String", )
OpenAPI.property_type(::Type{ UsageStorage }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UsageStorage[name]))}

function check_required(o::UsageStorage)
    o.value === nothing && (return false)
    o.unit === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ UsageStorage }, name::Symbol, val)
    if name === Symbol("value")
        OpenAPI.validate_param(name, "UsageStorage", :minimum, val, 0, false)
    end
end
