# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Collection_Spatial_Extent
The *potential* spatial extents of the features in the collection.

    CollectionSpatialExtent(;
        bbox=nothing,
    )

    - bbox::Vector{Vector} : One or more bounding boxes that describe the spatial extent of the dataset.  The first bounding box describes the overall spatial extent of the data. All subsequent bounding boxes describe more precise bounding boxes, e.g. to identify clusters of data. Clients only interested in the overall spatial extent will only need to access the first item in each array.
"""
Base.@kwdef mutable struct CollectionSpatialExtent <: OpenAPI.APIModel
    bbox::Union{Nothing, Vector{Vector}} = nothing

    function CollectionSpatialExtent(bbox, )
        OpenAPI.validate_property(CollectionSpatialExtent, Symbol("bbox"), bbox)
        return new(bbox, )
    end
end # type CollectionSpatialExtent

const _property_types_CollectionSpatialExtent = Dict{Symbol,String}(Symbol("bbox")=>"Vector{Vector}", )
OpenAPI.property_type(::Type{ CollectionSpatialExtent }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CollectionSpatialExtent[name]))}

function check_required(o::CollectionSpatialExtent)
    true
end

function OpenAPI.validate_property(::Type{ CollectionSpatialExtent }, name::Symbol, val)
    if name === Symbol("bbox")
        OpenAPI.validate_param(name, "CollectionSpatialExtent", :minItems, val, 1)
    end
end
