# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

module APIClient

using Dates, TimeZones
using OpenAPI
using OpenAPI.Clients

const API_VERSION = "1.2.0"

include("modelincludes.jl")

include("apis/api_AccountManagementApi.jl")
include("apis/api_BatchJobsApi.jl")
include("apis/api_CapabilitiesApi.jl")
include("apis/api_DataProcessingApi.jl")
include("apis/api_EODataDiscoveryApi.jl")
include("apis/api_FileStorageApi.jl")
include("apis/api_ProcessDiscoveryApi.jl")
include("apis/api_SecondaryServicesApi.jl")
include("apis/api_UserDefinedProcessesApi.jl")

end # module APIClient
